{% set domainNameNormalized = values.identifier.split(".")[0] | replace(r/[^\w]/g, "") %}
{% set dataProductNameNormalized = values.identifier.split(".")[1] | replace(r/[^\w]/g, "") %}
{% set dataProductMajorVersion = values.identifier.split(".")[2] | replace(r/[^\w]/g, "") %}
{% set componentNameNormalized = values.identifier.split(".")[3] | replace(r/[^\w]/g, "") %}
{% set ComponentDependencies = values.dependsOn | list if values.dependsOn else [] %}
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: ${{ values.description | dump }}
spec:
  mesh:
    description: ${{ values.description | dump }}
    dependsOn:
        {% if values.dependsOn | length > 0 %}
        {% for i in values.dependsOn %}
        - ${{ i }}
        {% endfor %}
        {% else %}{% endif %}
        {% if values.storageArea not in ComponentDependencies %}
        - ${{ values.storageArea }}
        {% endif %}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    readsFrom: {% if values.readsFrom | length > 0 %}{% for i in values.readsFrom %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific:
      # Default job name inside the job/src folder
      iamRole: ${{ values.iamRole }}
      workerType: ${{ values.workerType }}
      numberOfWorkers: ${{ values.numberOfWorkers }}
      executionClass: {% if values.isFlex == true %} FLEX {% else %} STANDARD {% endif %}
      storageAreaId: ${{ values.storageArea }}
      timeout: ${{ values.timeout }}
      warehouseLocation: ${{ values.warehouseLocation }}
      additionalJobParameters: {% if values.additionalJobParameters | length > 0 %}
      {% for param in values.additionalJobParameters %}
        - key: ${{ param.key }}
          value: ${{ param.value }}
      {% endfor %}{% else %}[]{% endif %}
      additionalSparkProperties: {% if values.additionalSparkProperties | length > 0 %}
      {% for param in values.additionalSparkProperties %}
        - key: ${{ param.key }}
          value: ${{ param.value }}
      {% endfor %}{% else %}[]{% endif %}
        

