apiVersion: witboost.com/v1
kind: EditTemplate
metadata:
  name: edit-aws-gluejob-template
  title: AWS Glue Job
  description: Creates a Glue job
  mesh:
    icon: https://d3g9o9u8re44ak.cloudfront.net/logo/40c0988b-b7ec-4c51-9732-5fd3c7d52928/96ad06d5-cf24-4ffe-94fb-5d3085d7d3eb.png
  tags:
    - aws
    - glue
    - gluejob
    - workload
spec:
  generates: componenttype:default/workload
  owner: agilelab
  useCaseTemplateId:
    - urn:dmb:utm:aws-gluejob-template:0.0.0
  type: workload
  
  parameters:
    - title: Update Workload
      description: |
        This wizard will allow you to edit the metadata for a previously created Workload.
        
        Most metadata is editable but some (like the name, domain, data product etc) are not; their fields will be read-only.
        
        Some of the files in the component's repository cannot be updated by this wizard, namely:
        - **Documentation**: `README.md`, `docs/index.md`, etc
        - **CI/CD**: `.gitlab-ci-yaml`
        You need to take care of updating these yourself, as given their nature it's hard to do automatically and they are often edited manually after the component's creation.
    
    - title: Update component metadata
      description: Basic information for this component.
      required:
        - description
      properties:
        name:
          title: Name
          type: string
          description: Not editable. The name of the component.
          ui:disabled: true
        description:
          title: Description
          type: string
          description: Help others understand what this Workload is for
          default: Workload that creates a Glue Job
        domain:
          title: Domain
          type: string
          description: Not editable. Domain of the Data Product this component belongs to
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
          ui:disabled: true
        dataproduct:
          title: Data Product
          type: string
          description: Not editable. Data Product this component belongs to
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
          ui:disabled: true
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:disabled: true
          
        developmentGroup:
          title: Development Group
          type: string
          description: Automatically selected from the Data Product metadata. Data Product development group.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        readsFrom:
          title: Reads from
          type: array
          default: []
          items:
            type: string
            ui:field: ReadsFromPicker
          description: This is filled only for DataPipeline workloads and it represents the list of output ports or external systems that is reading
        domainName:
          type: string
          ui:field: EntitySelectionPicker
          ui:fieldName: domain
          ui:property: spec.mesh.name
          ui:options:
            allowArbitraryValues: false
          ui:widget: hidden
        dataproductName:
          type: string
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.mesh.name
          ui:options:
            allowArbitraryValues: false
          ui:widget: hidden
        storageArea:
          title: Storage component dependency
          description: Not editable. AWS Glue job component must depend on a S3 Storage area component used for the script location
          type: string
          ui:disabled: true
          

    - title: Update Glue job details
      required:
        - region
        - timeout
      properties:
        region:
          title: Aws Region
          type: string
          description: Not editable. Aws region assigned to the Resource Group chosen above
          default: eu-west-1
          enum:
            - eu-west-1
            - eu-west-2
            - eu-west-3
            - eu-central-1
            - eu-north-1
            - eu-south-1
            - eu-south-2
            - eu-central-2
          enumNames:
            - Ireland (eu-west-1)
            - London (eu-west-2)
            - Paris (eu-west-3)
            - Frankfurt (eu-central-1)
            - Stockholm (eu-north-1)
            - Milan (eu-south-1)
            - Spain (eu-south-2)
            - Zurich (eu-central-2)
          ui:disabled: true
        timeout:
          description: The default is 480 minutes (8 hours) for a Glue 5.0 ETL job and 2,880 minutes (48 hours) for Glue 4.0 and below. No job timeout is defaulted for a Glue Streaming job.
          type: integer
          title: Job Timeout
          default: 480
        
    - title: Update Glue job resources
      required:
        - numberOfWorkers
        - workerType
      properties:
        numberOfWorkers:
          description: Number of workers
          title: Number of workers
          type: integer
          default: 2
        workerType:
          description: Set the type of predefined worker that is allowed when a job runs.
          title: Worker Type
          type: string
          default: G.1X
          enum:
              - G.1X
              - G.2X
              - G.4X
              - G.8X
          enumNames:
              - G.1X (4vCPUs, 16GB RAM)
              - G.2X (8vCPUs, 32GB RAM)
              - G.4X (16vCPUs, 64GB RAM)
              - G.8X (32CPUs, 128GB RAM)
        executionclass:
            title: Execution Class
            description: Reduce costs by running this job on spare capacity. Ideal for non-urgent workloads that don't require fast jobs start times or consistent execution times. See recommendations, limitations and pricing in the help panel by clicking on the Info link above.
            properties:
                isFlex:
                    title: Flex capacity
                    type: boolean
                    default: true
    - title: Catalog properties
      required:
        - catalog
        - warehouseLocation
      properties:
        catalog:
          description: Not editable. Catalog name, default is glue_catalog
          default: glue_catalog
          type: string
          ui:disabled: true
        warehouseLocation:
          description: Catalog warehouse location. It must be a relative path. It will be created within the dependant storage area.
          type: string
          default: the/wharehouse/location
    - title: Authorization
      required:
        - iamRole
      properties:
        iamRole:
          description: The IAM role arn used to run the job
          type: string
          default: arn::your:iam:role
    - title: Glue Job advanced settings
      properties:        
        additionalJobParameters:
          title: Additional parameters
          description: |
            Here you can define additional [glue job parameters](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html), for example to provide inputs for your job. 
            Beware that a number of parameters is injected at deployment time. 
            Refer to the documentation of this template for more on this.
          type: object
          properties:
            jobparameters:
              title: Parameters
              type: array
              ui:ArrayFieldTemplate: ArrayTableTemplate
              items:
                type: object
                ui:ObjectFieldTemplate: TableRowTemplate
                required:
                  - key
                  - value
                properties:
                  key:
                    type: string
                    title: Key
                  value:
                    type: string
                    title: Value
        
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          name: '${{ parameters.name }}'
          domainName: '${{ parameters.domainName }}'
          dataproductName: '${{ parameters.dataproductName }}'
          description: '${{ parameters.description }}'
          domain: '${{ parameters.domain }}'
          dataproduct: '${{ parameters.dataproduct }}'
          identifier: '${{ parameters.identifier }}'
          developmentGroup: '${{ parameters.developmentGroup }}'
          readsFrom: '${{ parameters.readsFrom }}'
          tags: '${{ parameters.tags }}'
          region: '${{ parameters.region }}'
          workerType: '${{ parameters.workerType }}'
          isFlex: '${{ parameters.executionclass.isFlex }}'
          timeout: '${{ parameters.timeout }}'
          numberOfWorkers: '${{ parameters.numberOfWorkers }}'
          scriptName: main.py
          catalogName: '${{ parameters.catalog }}'
          warehouseLocation: '${{ parameters.warehouseLocation }}'
          iamRole: '${{ parameters.iamRole }}'
          additionalJobParameters: '${{ parameters.additionalJobParameters.jobparameters }}'
          storageArea: '${{parameters.storageArea}}'
          useCaseTemplateId: urn:dmb:utm:aws-gluejob-template:0.0.0
          infrastructureTemplateId: urn:dmb:itm:aws-gluejob-provisioner:0
          useCaseTemplateVersion: 0.0.0
          organizationName: AgileDMBSandbox
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          