apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-gluejob-template
  title: AWS Glue Job
  description: Creates a Glue job
  mesh:
    icon: https://d3g9o9u8re44ak.cloudfront.net/logo/40c0988b-b7ec-4c51-9732-5fd3c7d52928/96ad06d5-cf24-4ffe-94fb-5d3085d7d3eb.png
  tags:
    - aws
    - glue
    - gluejob
    - workload
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  generates: componenttype:default/workload
  owner: agilelab
  type: workload
  parameters:
    - title: Component metadata
      description: Basic information for this component.
      required:
        - name
        - domain
        - dataproduct
        - description
        - storageArea
      properties:
        name:
          title: Name
          type: string
          description: Required. The name of the component.
          ui:field: EntityNamePicker
          default: Glue Job
          ui:options:
            allowArbitraryValues: true
        description:
          title: Description
          type: string
          description: Help others understand what this Workload is for
          default: Workload that creates a Glue Job
        domain:
          title: Domain
          type: string
          description: Required. Domain of the Data Product this component belongs to.
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
        dataproduct:
          title: Data Product
          type: string
          description: Required. Data Product this component belongs to.
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:field: ComponentIdentifierPicker
          ui:options:
            allowArbitraryValues: false
        developmentGroup:
          title: Development Group
          type: string
          description: Automatically selected from the Data Product metadata. Data Product development group.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        readsFrom:
          title: Reads from
          type: array
          default: []
          items:
            type: string
            ui:field: ReadsFromPicker
          description: This is filled only for DataPipeline workloads and it represents the list of output ports or external systems that is reading
        domainName:
          type: string
          ui:field: EntitySelectionPicker
          ui:fieldName: domain
          ui:property: spec.mesh.name
          ui:options:
            allowArbitraryValues: false
          ui:widget: hidden
        dataproductName:
          type: string
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.mesh.name
          ui:options:
            allowArbitraryValues: false
          ui:widget: hidden
        storageArea:
          title: Storage component dependency
          description: AWS Glue job component must depend on a S3 Storage area component used for the script location
          type: string
          ui:field: EntityRelationsPicker
          ui:fieldName: dataproduct
          relation: hasPart
          ui:filters:
            - key: spec.mesh.useCaseTemplateId
              value: "urn:dmb:utm:aws-s3-template:0.0.0"

    - title: Glue job details
      required:
        - region
        
      properties:
        region:
          title: Aws Region
          type: string
          description: Aws region assigned to the Resource Group chosen above
          default: eu-west-1
          enum:
            - eu-west-1
            - eu-west-2
            - eu-west-3
            - eu-central-1
            - eu-north-1
            - eu-south-1
            - eu-south-2
            - eu-central-2
          enumNames:
            - Ireland (eu-west-1)
            - London (eu-west-2)
            - Paris (eu-west-3)
            - Frankfurt (eu-central-1)
            - Stockholm (eu-north-1)
            - Milan (eu-south-1)
            - Spain (eu-south-2)
            - Zurich (eu-central-2)

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          name: '${{ parameters.name }}'
          domainName: '${{ parameters.domainName }}'
          dataproductName: '${{ parameters.dataproductName }}'
          description: '${{ parameters.description }}'
          domain: '${{ parameters.domain }}'
          dataproduct: '${{ parameters.dataproduct }}'
          identifier: '${{ parameters.identifier }}'
          developmentGroup: '${{ parameters.developmentGroup }}'
          readsFrom: '${{ parameters.readsFrom }}'
          tags: '${{ parameters.tags }}'
          region: '${{ parameters.region }}'
          workerType: G.1X
          numberOfWorkers: 2
          timeout: 480
          iamRole: arn::your:iam:role
          warehouseLocation: the/wharehouse/location
          isFlex: true
          scriptName: main.py
          catalogName: glue_catalog
          storageArea: '${{parameters.storageArea}}'
          useCaseTemplateId: urn:dmb:utm:aws-gluejob-template:0.0.0
          infrastructureTemplateId: urn:dmb:itm:aws-gluejob-provisioner:0
          useCaseTemplateVersion: 0.0.0
          organizationName: AgileDMBSandbox
          destination: &destination 'gitlab.com?owner=AgileDMBSandbox%2F${{orgname}}%2Fmesh.repository%2F${{ parameters.domain | replace(r/domain:| |-/, "") }}%2F${{ parameters.dataproduct.split(".")[1] | replace(r/ |-/g, "") }}&repo=${{ parameters.name.split(" ") | join("") | lower }}'


    - id: publish
      name: Publish
      action: witboostMeshComponent:publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: 'This is ${{ parameters.name }}'
        repoUrl: *destination
        rootDirectory: ${{ parameters.rootDirectory }}
        dataproduct: '${{ parameters.dataproduct }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: /${{ parameters.rootDirectory }}/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: '${{ steps.publish.output.remoteUrl }}'
      - title: Open in catalog
        icon: catalog
        entityRef: '${{ steps.register.output.entityRef }}'
