{% set dataProductName = values.dataproduct.split(".")[1] %}
{% set domainNameNormalized = values.domain | replace(r/domain:| |-/, "") %}
{% set dataProductMajorVersion = values.identifier.split(".")[2] | replace(r/[^\w]/g, "") %}
{% set componentNameNormalized = values.identifier.split(".")[3] | replace(r/[^\w]/g, "") %}
{% set storageComponentNameNormalized = values.storageArea.split(":")[6] %}


stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  image: python:3.9
  script:
    - cd job
    - pip install flake8 black
    - flake8 --ignore F403,F405,E501
    - black --check .

pytest:
  stage: test
  variables:
    DATALAKE_FORMATS: iceberg
  image: 
    name: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    entrypoint: [""]
  script:
    - cd job
    - python3 -m pip install -r tests/requirements-test.txt
    - python3 -m pip install -r src/requirements.txt
    - python3 -m pytest tests/

.deploy:
  tags: ["gitlab-runner-private-tag"]
  stage: deploy
  image: 
    name: amazon/aws-cli:2.23.4
    entrypoint: [""]
  script:
    # Compute bucket name
    - |
      source ./ci-utils/compute-bucket-name.sh
      S3_BUCKET=$(compute_bucket_name ${{domainNameNormalized}} ${{dataProductName}} ${{storageComponentNameNormalized}} "$environment")
      echo "Deploying to bucket: $S3_BUCKET"
    # Upload artifact  
    - aws s3 cp job/src/main.py s3://$S3_BUCKET/v${{dataProductMajorVersion}}/glue-jobs/${{componentNameNormalized}}/main.py

deploy-development:
  extends: .deploy
  variables:
    environment: development

deploy-qa:
  extends: .deploy
  variables:
    environment: qa
  when: manual

deploy-production:
  extends: .deploy
  variables:
    environment: production
  when: manual